/**
 * prose-generate — pure logic (no Deno APIs, no secrets). The Deno.serve
 * wiring and the ONLY code path holding ANTHROPIC_API_KEY live in index.ts.
 *
 * Everything here is deterministic and unit-tested:
 *   stripForStrict     schema sent to the API (strict mode rejects bounds)
 *   constraintNotes    the REQUIRED plain-language re-issue of those bounds
 *   fillTemplate       {placeholder} → input_data value (dot paths, arrays)
 *   resolveGuards      guard tokens ({linking} → the number) so gates stay
 *                      domain-blind
 *   coerceToSchema     cheap second line of defense after strict mode
 *   validateSchema     structural check mirroring what strict mode enforced
 *   generateItem       the per-item flow with injected db/llm deps
 */

import { dataHash } from '../_shared/hash.ts';
import {
  runItemGates,
  hasFailingGate,
  type GateResult,
} from '../_shared/gates/index.ts';

// ── Schema handling ──────────────────────────────────────────────────────────

/** Constraint keywords Anthropic's strict mode rejects inside input_schema. */
const STRICT_REJECTED_KEYWORDS = [
  'minItems', 'maxItems', 'minLength', 'maxLength', 'pattern',
  'minimum', 'maximum', 'exclusiveMinimum', 'exclusiveMaximum', 'multipleOf',
] as const;

/**
 * Deep-clone the template's output_schema and remove every constraint keyword
 * strict mode rejects. Also enforce what strict mode REQUIRES on every object:
 * `additionalProperties: false` and a `required` array (defaulting to all
 * declared properties).
 *
 * The dropped constraints are NOT lost — constraintNotes() re-issues them as
 * prose (ground rule 5; skipping that failed ~⅓ of items in the reference
 * project's first full batch).
 */
export function stripForStrict(schema: unknown): unknown {
  if (schema === null || typeof schema !== 'object') return schema;
  if (Array.isArray(schema)) return schema.map(stripForStrict);

  const src = schema as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(src)) {
    if ((STRICT_REJECTED_KEYWORDS as readonly string[]).includes(k)) continue;
    out[k] = stripForStrict(v);
  }
  if (out.type === 'object' && typeof out.properties === 'object' && out.properties !== null) {
    out.additionalProperties = false;
    if (!Array.isArray(out.required)) out.required = Object.keys(out.properties);
  }
  return out;
}

export interface Guards {
  [gate: string]: Record<string, unknown> | undefined;
}

/**
 * Render every bound that stripForStrict dropped — plus the length /
 * required-mention / faq-shape guards — as plain-language RÀNG BUỘC lines.
 * Placeholder tokens ({lifePath}, {linking}, …) are left intact; the caller
 * runs fillTemplate over the final prompt, resolving them from input_data.
 * Generated by walking the config, never hardcoded per tenant.
 */
export function constraintNotes(schema: unknown, guards: Guards): string {
  const lines: string[] = [];

  const length = guards.length as { fields?: Record<string, [number, number]> } | undefined;
  for (const [field, [min, max]] of Object.entries(length?.fields ?? {})) {
    lines.push(`- ${field}: ${min}–${max} ký tự`);
  }

  // Array bounds from the ORIGINAL (un-stripped) schema.
  const props = (schema as { properties?: Record<string, Record<string, unknown>> })?.properties ?? {};
  for (const [field, def] of Object.entries(props)) {
    if (def.type !== 'array') continue;
    const min = def.minItems as number | undefined;
    const max = def.maxItems as number | undefined;
    if (min !== undefined && min === max) lines.push(`- ${field}: ĐÚNG ${min} phần tử`);
    else if (min !== undefined || max !== undefined) {
      lines.push(`- ${field}: ${min ?? 'không giới hạn dưới'}–${max ?? 'không giới hạn trên'} phần tử`);
    }
  }

  const faq = guards.faq_shape as { count?: number; answers_must_contain?: string[] } | undefined;
  if (faq?.count !== undefined) lines.push(`- faqs: ĐÚNG ${faq.count} phần tử`);
  for (const token of faq?.answers_must_contain ?? []) {
    lines.push(`- faqs: ít nhất một câu trả lời phải nêu đúng con số ${token}`);
  }

  const mentions = guards.required_mentions as
    | { rules?: Array<{ field: string; must_contain: string[] }> }
    | undefined;
  for (const rule of mentions?.rules ?? []) {
    lines.push(`- ${rule.field}: phải chứa ${rule.must_contain.join(' và ')}`);
  }

  const banned = guards.banned_phrases as { list?: string[] } | undefined;
  if (banned?.list?.length) {
    lines.push(`- TUYỆT ĐỐI KHÔNG dùng các cụm: ${banned.list.map((p) => `"${p}"`).join(', ')}`);
  }

  if (lines.length === 0) return '';
  return ['RÀNG BUỘC ĐỘ DÀI & SỐ LƯỢNG — tuân thủ tuyệt đối:', ...lines].join('\n');
}

/** Look up a dot path ("lp.archetype") in input_data. */
function lookupPath(data: Record<string, unknown>, path: string): unknown {
  let cur: unknown = data;
  for (const part of path.split('.')) {
    if (cur === null || typeof cur !== 'object') return undefined;
    cur = (cur as Record<string, unknown>)[part];
  }
  return cur;
}

function renderValue(v: unknown): string {
  if (Array.isArray(v)) return v.map(renderValue).join(', ');
  if (v === null || v === undefined) return '';
  return String(v);
}

/**
 * Fill {placeholder} tokens (dot paths allowed) from input_data. Unknown
 * tokens THROW — a template referencing a fact that doesn't exist must fail
 * the generation, not ship a literal "{lifePath}" into prose.
 */
export function fillTemplate(template: string, data: Record<string, unknown>): string {
  return template.replace(/\{([a-zA-Z_][a-zA-Z0-9_.]*)\}/g, (_, path: string) => {
    const v = lookupPath(data, path);
    if (v === undefined) throw new Error(`[prose-generate] template placeholder {${path}} not found in input_data`);
    return renderValue(v);
  });
}

/**
 * Resolve guard placeholder tokens from input_data so the generic gates never
 * learn the domain: {"must_contain": ["{linking}"]} → ["4"]. Applied to every
 * string anywhere in the guards JSON.
 */
export function resolveGuards(guards: Guards, data: Record<string, unknown>): Guards {
  const resolve = (v: unknown): unknown => {
    if (typeof v === 'string') {
      return v.replace(/\{([a-zA-Z_][a-zA-Z0-9_.]*)\}/g, (m, path: string) => {
        const found = lookupPath(data, path);
        return found === undefined ? m : renderValue(found);
      });
    }
    if (Array.isArray(v)) return v.map(resolve);
    if (v !== null && typeof v === 'object') {
      return Object.fromEntries(Object.entries(v as Record<string, unknown>).map(([k, x]) => [k, resolve(x)]));
    }
    return v;
  };
  return resolve(guards) as Guards;
}

/**
 * Cheap second line of defense (§6.4): strict mode + constraint notes should
 * make this a no-op, but re-parse stringified arrays/objects back into real
 * ones when the schema expects them.
 */
export function coerceToSchema(raw: unknown, schema: unknown): unknown {
  const def = schema as Record<string, unknown> | null;
  if (def === null || typeof def !== 'object') return raw;

  if ((def.type === 'array' || def.type === 'object') && typeof raw === 'string') {
    try {
      const parsed = JSON.parse(raw);
      return coerceToSchema(parsed, def);
    } catch {
      return raw;
    }
  }
  if (def.type === 'array' && Array.isArray(raw)) {
    return raw.map((item) => coerceToSchema(item, def.items));
  }
  if (def.type === 'object' && raw !== null && typeof raw === 'object' && !Array.isArray(raw)) {
    const props = (def.properties ?? {}) as Record<string, unknown>;
    const out: Record<string, unknown> = { ...(raw as Record<string, unknown>) };
    for (const [k, propDef] of Object.entries(props)) {
      if (k in out) out[k] = coerceToSchema(out[k], propDef);
    }
    return out;
  }
  return raw;
}

/**
 * Minimal structural validator over the subset of JSON Schema the templates
 * use (type/object/array/required/additionalProperties/enum). Length and
 * numeric bounds are the length/numeric gates' job, not this one's.
 */
export function validateSchema(value: unknown, schema: unknown, path = '$'): string[] {
  const def = schema as Record<string, unknown> | null;
  if (def === null || typeof def !== 'object') return [];
  const errors: string[] = [];
  const t = def.type as string | undefined;

  const typeOk = (): boolean => {
    switch (t) {
      case 'object': return value !== null && typeof value === 'object' && !Array.isArray(value);
      case 'array': return Array.isArray(value);
      case 'string': return typeof value === 'string';
      case 'number': return typeof value === 'number';
      case 'integer': return typeof value === 'number' && Number.isInteger(value);
      case 'boolean': return typeof value === 'boolean';
      case 'null': return value === null;
      default: return true;
    }
  };
  if (!typeOk()) {
    errors.push(`${path}: expected ${t}, got ${Array.isArray(value) ? 'array' : typeof value}`);
    return errors;
  }

  if (Array.isArray(def.enum) && !def.enum.some((e) => e === value)) {
    errors.push(`${path}: not in enum`);
  }

  if (t === 'object') {
    const obj = value as Record<string, unknown>;
    const props = (def.properties ?? {}) as Record<string, unknown>;
    for (const req of (def.required as string[] | undefined) ?? []) {
      if (!(req in obj)) errors.push(`${path}.${req}: required property missing`);
    }
    if (def.additionalProperties === false) {
      for (const k of Object.keys(obj)) {
        if (!(k in props)) errors.push(`${path}.${k}: additional property not allowed`);
      }
    }
    for (const [k, propDef] of Object.entries(props)) {
      if (k in obj) errors.push(...validateSchema(obj[k], propDef, `${path}.${k}`));
    }
  }
  if (t === 'array' && def.items !== undefined) {
    (value as unknown[]).forEach((item, i) => errors.push(...validateSchema(item, def.items, `${path}[${i}]`)));
  }
  return errors;
}

// Domain input builder lives in _shared/inputs.ts (prose-admin needs the same
// builder to create pending items); re-exported here for the generate flow.
export { buildComboInput } from '../_shared/inputs.ts';

/** Deterministic review sampling: same item_key always samples the same way. */
export function reviewSampleHit(itemKey: string, pct: number): boolean {
  if (pct >= 100) return true;
  if (pct <= 0) return false;
  let h = 0;
  for (const c of itemKey) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return h % 100 < pct;
}

// ── faq_shape gate (config-driven, merged with the generic per-item gates) ───

export function gateFaqShape(
  output: Record<string, unknown>,
  cfg: { count?: number; answers_must_contain?: string[] } | undefined,
): GateResult {
  const faqs = output.faqs as Array<{ q?: unknown; a?: unknown }> | undefined;
  const viol: string[] = [];
  if (!Array.isArray(faqs)) {
    viol.push('faqs missing or not an array');
  } else {
    if (cfg?.count !== undefined && faqs.length !== cfg.count) {
      viol.push(`expected exactly ${cfg.count} faqs, got ${faqs.length}`);
    }
    for (const f of faqs) {
      if (typeof f?.q !== 'string' || typeof f?.a !== 'string') viol.push('faq entry missing q/a');
    }
    for (const token of cfg?.answers_must_contain ?? []) {
      if (!faqs.some((f) => typeof f?.a === 'string' && f.a.includes(token))) {
        viol.push(`no faq answer contains "${token}"`);
      }
    }
  }
  return { gate: 'faq_shape', severity: 'fail', passed: viol.length === 0,
           detail: viol.join('; ') || undefined };
}

// ── Per-item orchestration with injected deps ────────────────────────────────

export interface TemplateRow {
  id: string;
  site_id: string;
  key: string;
  version: number;
  system_prompt: string;
  user_template: string;
  output_schema: Record<string, unknown>;
  few_shots: unknown[];
  guards: Guards;
  model: string;
  temperature: number;
  max_tokens: number;
}

export interface ItemRow {
  id: string;
  site_id: string;
  job_id: string;
  template_key: string;
  template_version: number;
  item_key: string;
  data_hash: string;
  input_data: Record<string, unknown>;
  output: Record<string, unknown> | null;
  status: string;
  validation: Record<string, unknown>;
  regen_count: number;
}

export interface LlmRequest {
  model: string;
  system: string;
  userPrompt: string;
  toolSchema: Record<string, unknown>;
  temperature: number;
  maxTokens: number;
}

export interface LlmResult {
  output: unknown;
  tokensIn: number;
  tokensOut: number;
}

export interface GenerateDeps {
  getItem(itemId: string): Promise<ItemRow | null>;
  getTemplate(siteId: string, key: string, version: number): Promise<TemplateRow | null>;
  saveResult(item: ItemRow, patch: {
    output: Record<string, unknown>;
    status: string;
    validation: Record<string, unknown>;
    regen_count: number;
  }): Promise<void>;
  addJobUsage(jobId: string, tokensIn: number, tokensOut: number): Promise<void>;
  getJobReviewPct(jobId: string): Promise<number>;
  llm(req: LlmRequest): Promise<LlmResult>;
}

export interface GenerateRequest {
  item_id: string;
  mode?: 'generate' | 'regenerate';
}

/**
 * Assemble the per-item gate results for an output against a template + its
 * input_data: schema, the generic per-item gates over resolved guards, and
 * faq_shape. Used by generateItem AND by prose-admin's edit handler (so a
 * reviewer edit is re-gated — the fail-gate publish guarantee must hold for
 * edited_output, not just the original output). Batch gates are separate.
 */
export function assembleItemGates(
  output: Record<string, unknown>,
  template: { output_schema: Record<string, unknown>; guards: Record<string, unknown> },
  inputData: Record<string, unknown>,
): GateResult[] {
  const guards = template.guards as Guards;
  const resolved = resolveGuards(guards, inputData);
  const gates: GateResult[] = [];
  if (guards.schema !== undefined) {
    const errs = validateSchema(output, template.output_schema);
    gates.push({ gate: 'schema', severity: 'fail', passed: errs.length === 0,
                 detail: errs.slice(0, 8).join('; ') || undefined });
  }
  const computedCfg = guards.numeric_consistency as { computed?: string[] } | undefined;
  const computed: Record<string, number> = {};
  for (const field of computedCfg?.computed ?? []) {
    const v = inputData[field];
    if (typeof v === 'number') computed[field] = v;
  }
  gates.push(...runItemGates({ output, guards: resolved, computed }));
  if (guards.faq_shape !== undefined) {
    gates.push(gateFaqShape(output, resolved.faq_shape as { count?: number; answers_must_contain?: string[] }));
  }
  return gates;
}

/**
 * Generate exactly ONE item: cache check → prompt build (constraint notes are
 * NOT optional) → forced strict tool call → coerce → gates → persist status.
 */
export async function generateItem(deps: GenerateDeps, req: GenerateRequest): Promise<{
  ok: boolean;
  status?: string;
  cached?: boolean;
  item_key?: string;
  error?: string;
  gates?: GateResult[];
}> {
  const item = await deps.getItem(req.item_id);
  if (!item) return { ok: false, error: `item ${req.item_id} not found` };

  // Cache: the row's data_hash was computed from input_data at job creation.
  // A regenerated fact-set produces a different hash → a different row →
  // this row would have been superseded. Same row + already generated output
  // + not regenerate mode → return cached, zero LLM tokens.
  const expectedHash = await dataHash(item.input_data);
  if (expectedHash !== item.data_hash) {
    return { ok: false, error: `data_hash drift on ${item.item_key}: stored input_data no longer matches its hash` };
  }
  if (item.output && item.status !== 'pending' && req.mode !== 'regenerate') {
    return { ok: true, status: item.status, cached: true, item_key: item.item_key };
  }

  const template = await deps.getTemplate(item.site_id, item.template_key, item.template_version);
  if (!template) {
    return { ok: false, error: `template ${item.template_key} v${item.template_version} not found` };
  }

  // Build the prompt. constraint_notes is substituted first, then ONE fill
  // pass resolves every {token} — including tokens inside the notes.
  const notes = constraintNotes(template.output_schema, template.guards);
  const withNotes = template.user_template.includes('{constraint_notes}')
    ? template.user_template.replace('{constraint_notes}', notes)
    : `${template.user_template}\n\n${notes}`;
  const userPrompt = fillTemplate(withNotes, item.input_data);

  let system = template.system_prompt;
  const fewShots = (template.few_shots ?? []).filter(
    // Never few-shot the combo being generated (WP6 distillation rule).
    (shot) => !(shot && typeof shot === 'object' && (shot as { item_key?: string }).item_key === item.item_key),
  );
  if (fewShots.length > 0) {
    system += '\n\nVÍ DỤ THAM KHẢO (giọng văn & cấu trúc — KHÔNG chép lại nội dung, dữ kiện thuộc về tổ hợp khác):\n' +
      fewShots.map((s, i) => `--- Ví dụ ${i + 1} ---\n${JSON.stringify((s as { output?: unknown }).output ?? s)}`).join('\n');
  }

  const llmResult = await deps.llm({
    model: template.model,
    system,
    userPrompt,
    toolSchema: stripForStrict(template.output_schema) as Record<string, unknown>,
    temperature: template.temperature,
    maxTokens: template.max_tokens,
  });
  await deps.addJobUsage(item.job_id, llmResult.tokensIn, llmResult.tokensOut);

  const output = coerceToSchema(llmResult.output, template.output_schema) as Record<string, unknown>;

  // Gates: schema (mirrors strict mode), generic per-item gates over resolved
  // guards, faq_shape. Batch gates run later in prose-admin.
  const gates = assembleItemGates(output, template, item.input_data);

  const reviewPct = await deps.getJobReviewPct(item.job_id);
  const anyFail = hasFailingGate(gates);
  const anyFlag = gates.some((g) => g.severity === 'flag' && !g.passed);
  const sampled = reviewSampleHit(item.item_key, reviewPct);
  const status = anyFail ? 'failed_validation' : anyFlag || sampled ? 'flagged' : 'generated';

  await deps.saveResult(item, {
    output,
    status,
    validation: { gates, review_sampled: sampled },
    regen_count: req.mode === 'regenerate' ? item.regen_count + 1 : item.regen_count,
  });

  return { ok: true, status, cached: false, item_key: item.item_key, gates };
}
